; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = IROCK_212_v1_0, IROCK_212_v1_1
description = iRock 212 OS

[env]
platform = ststm32
framework = arduino
lib_ldf_mode = deep+
monitor_speed = 115200

[extra]
lib_deps_external =
	davetcc/TaskManagerIO@^1.3.0
	stm32duino/STM32duino Low Power@^1.1.1
	stm32duino/STM32duino RTC@^1.2.0
	bxparks/AceSorting@^1.0.0
	iRock/MappingIO@^0.0.8
	iRock/CLI@^0.0.19
	iRock/BatShutOff@^0.0.22
	iRock/Balancer@^0.0.17
	iRock/SSRSwitcher@^1.0.0
build_flags_external =
	-Iinclude
	-D MAPPING_IO_PIN_LIST=\"PinList.h\"
	-D MAPPING_IO_SIGNAL_LIST=\"SignalList.h\"
	-D MAPPING_IO_MAPPING_LIST=\"MappingList.h\"
	-D BAT_SHUTOFF_SIGNAL_LIST=\"BatShutOffList.h\"
	-D BALACER_SIGNAL_LIST=\"BalancerList.h\"
	-D SSRSWITCHER_SIGNAL_LIST=\"SSRSwitcherList.h\"
	-D CURRENT_TIME=$UNIX_TIME
	-D TM_ENABLE_CAPTURED_LAMBDAS
	-D SW_VERSION=1.0.0


[env:IROCK_212_v1_0]
board = IROCK_212_v1_0
lib_deps = 
	lib/IROCK_212_V1_0
	${extra.lib_deps_external}
build_flags =
	${extra.build_flags_external}

[env:IROCK_212_v1_1]
board = IROCK_212_v1_1
lib_deps = 
	lib/IROCK_212_V1_1
	${extra.lib_deps_external}
build_flags =
	${extra.build_flags_external}
